### PR TITLE
fix: use byte col to call extmarks api

### PR DESCRIPTION
**Pull request by mrbeardad**
Neovim use 3 kinds of column:
1. Byte column, 0-based index, this is used for most of nvim.api, include extmarks api
2. Character column, 1-based index, this is used for cursor left/right move, and is used in this plugin
3. Virtual column, 1-based index, this is used for cursor up/down move, `curswant` is a virtual column but not a character column

For example,
```txt
1234567
abc你好
```

`你` has `3` bytes, `1` chracter and `2` display width. So
- its byte column is `3` (start byte index)
- its character column is `4`
- its virtual column is `5` (end virtual column)

In this pr, I've convert all `vc.col` into byte column when call extmarks api.
However, there are too many `vc.curswant = vc.col`, so I make the pr to discuss the solution for it.

### CODE REVIEW

**Comment by mrbeardad** [comment]
No. The problem about column for extmarks api has been solved with this pr, the remaining problem is,
`curswant` is a virtual column, it is relative with character display width, and affect up/down motion.
All `vc.col = vc.curswant` is wrong, it needs to be converted first.

**Comment by mrbeardad** [comment]
>
> ```lua
> local text = vim.fn.strcharpart(vim.fn.getline(lnum), 0, col)
> local virtcol = vim.fn.strdisplaywidth(text)
> ```

However, the behavior is slightly different from the builtin motion, becase when cursor at a character that has 2-char display width, the curswant can be either the first char or the second char.

```txt
12
你
```
The `curswant` of cursor that on `你` is `1` if it has moved down from `1`, or `2` from `2`. so always recover `vc.curswant` from `vc.col` is not a good idea

**Comment by mrbeardad** [comment]
image

The `display width` needs to be considered when set `end_col`, check [this](https://github.com/brenton-leighton/multiple-cursors.nvim/pull/14/files#diff-459f58b3ee2f3b8bc7bafa4e5d70456c737e5eb1d6059c385bec77ca43677aecR39)

**Comment by mrbeardad** [comment]
Left/Right motion use character column, up/down motion use virtual column(display width).
Why don't use normal command to move cursor? Thus, user setting could be considered automatically, such as [`whichwrap`](https://neovim.io/doc/user/options.html#'whichwrap'),

**Comment by brenton-leighton** [comment]
> Left/Right motion use character column, up/down motion use virtual column(display width).

What do you mean by virtual column? The curswant value?

> Why don't use normal command to move cursor?

Originally I tried using `virtualedit = "onemore"` for insert mode but it didn't seem to work. I thought it was because setting the option wasn't "api-fast" (so it would occur in the event loop like `feedkeys`). I think I realise now that the issue is that the `$` command doesn't work in insert mode even with `virtualedit="onemore`.

> Thus, user setting could be considered automatically, such as [`whichwrap`](https://neovim.io/doc/user/options.html#'whichwrap'),

I'll try changing things to use "onemore" and `whichwrap`

**Comment by mrbeardad** [comment]
> What do you mean by virtual column? The curswant value?

Virtual column is the last screen position occupied by the character at that position, different unicode character maybe has different display width. For example, the display width of `a` is 1, and `你` is 2, so `a` occupies 1 screen column, `你` occupies 2 screen column. The virtual column of `a` is ` and `你` is 5.

```txt
1234567
abc你好
```

Assuming the cursor is at `好`, the curswant of the cursor is 6, the virtual column of `好` is 7. Then you moved the cursor up and it was placed on the `6` where the virtual colmun equal to the curswant.

**Pull request closed without merging**
